# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boot_cor <- function(x, y, n_boot, conf) {
    .Call('_bfstat_boot_cor', PACKAGE = 'bfstat', x, y, n_boot, conf)
}

boot_cor_null <- function(x, y, n_boot, conf) {
    .Call('_bfstat_boot_cor_null', PACKAGE = 'bfstat', x, y, n_boot, conf)
}

